project:
  type: website
  render:
    - "**/*.md"
website:
  title: "Onesmus Wachira Kabui - Resume"
  google-analytics: 'G-GH4C7E17TM'
  site-url: https://onesmus.com
  description: "Onesmus Wachira Kabui - Resume"
  page-footer:
    border: true
    background: dark
    center: 
      - text: "<b>Download PDF</b>"
        href: /index.pdf
      - text: "ask@onesmus.com"
        href: mailto:ask@onesmus.com
format-links: false
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
  pdf: default
resources:
  - CNAME



